# Generated by Django 5.2.5 on 2026-09-15 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfeedback', '0008_storedexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='second_feedback_enabled',
            field=models.BooleanField(default=False, help_text='Allow students to submit the second feedback round for this form.'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='feedback_round',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Feedback 1'), (2, 'Feedback 2')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together={('form', 'student', 'feedback_round')},
        ),
        migrations.CreateModel(
            name='UserMailSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_address', models.EmailField(max_length=254)),
                ('app_password', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_setup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
